### ISSUE TITLE
Mark album as AOTM

### ISSUE THREAD

**Issue by rsnorman** [rsnorman/julysoundcheck#9]
Have the ability to mark and album as Album Of The Month (AOTM) will help after month of July is over. Should have page that shows all AOTMs

**Comment by rsnorman** [comment]
Should there be validation that only lets one AOTM per user per year?

**Comment by mathyoumore** [comment]
Frequently people do a short-list of AOTMs, so maybe an indicator of AOTM-ness instead of restricting people to one.
